"""Compare explicit FTCS and Crank–Nicolson on the same diffusion model."""

import argparse
import json
from pathlib import Path

from run_study import plt, write_csv, save_figure
import numpy as np

from diffusion import analytical_profile, solve_slab, solve_slab_cn


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path('results'))
    directory = parser.parse_args().output
    directory.mkdir(exist_ok=True)
    plt.rcParams['svg.hashsalt'] = 'diffusion-method-comparison'
    nodes, tau = 81, 0.05
    rows = []
    curves = []
    for method, solver, ratios in [
        ('FTCS', solve_slab, [0.1, 0.25, 0.45]),
        ('Crank-Nicolson', solve_slab_cn, [0.1, 0.25, 0.45, 1, 2, 4, 8]),
    ]:
        for r in ratios:
            state = solver([tau], nodes=nodes, r=r)[0]
            error = float(np.max(np.abs(state.concentration-analytical_profile(state.position, tau))))
            steps = int(np.ceil(tau/(r/(nodes-1)**2)))
            actual_r = (tau/steps)*(nodes-1)**2
            rows.append((method, r, actual_r, steps, error))
            if (method == 'FTCS' and r == 0.45) or (method == 'Crank-Nicolson' and r in [1, 8]):
                curves.append((method, r, state))
    write_csv(directory/'method_comparison.csv', ['method', 'maximum_r', 'actual_r', 'time_steps', 'max_abs_error'], rows)
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.3), layout='constrained')
    for method, r, state in curves:
        axes[0].plot(state.position, state.concentration, label=f'{method}, r ≤ {r:g}')
    axes[0].plot(state.position, analytical_profile(state.position, tau), 'k--', lw=1, label='Analytical series')
    axes[0].set(xlabel='Position x/L', ylabel='C/Cs', title='Same boundary and initial conditions')
    axes[0].legend(fontsize=8)
    for method, marker in [('FTCS', 'o'), ('Crank-Nicolson', 's')]:
        selected=[row for row in rows if row[0]==method]
        axes[1].loglog([row[2] for row in selected], [row[4] for row in selected], marker+'-', label=method)
    axes[1].axvline(0.5, ls=':', color='#555555', label='FTCS stability limit')
    axes[1].set(xlabel='Actual ΔFo/(Δx/L)²', ylabel='Maximum absolute error in C/Cs', title='Accuracy depends on the chosen time step')
    axes[1].legend(fontsize=8)
    fig.suptitle('Time-stepping comparison — simulated slab, 81 nodes, Fo = 0.05', fontsize=13)
    save_figure(fig, directory, 'method_comparison')
    report='''# Explicit and implicit time stepping

Generated by `python compare_methods.py`. The same idealized slab is solved at Fo=0.05 with 81 nodes using explicit FTCS and Crank–Nicolson (CN).

![Method comparison](method_comparison.png)

| Method | Maximum r | Actual r | Steps | Max. absolute error |
| --- | ---: | ---: | ---: | ---: |
'''+ '\n'.join(f'| {method} | {r:g} | {actual:.6f} | {steps} | {error:.3e} |' for method,r,actual,steps,error in rows)+'''

FTCS requires r≤0.5 for stability. CN is linearly stable for larger ratios, but this does not guarantee accuracy or non-negative, monotone profiles. A sudden surface-concentration jump can excite oscillations with coarse CN steps. The tests include a deliberately coarse example that overshoots the physical concentration range, rather than clipping it.

The error includes spatial discretization, time stepping, and the initial boundary discontinuity. Error cancellation can make it non-monotonic in the step size. The table is not a general claim that either method is always more accurate or faster. Step counts are reported; no execution-speed benchmark is claimed.

The standard CN method was independently implemented here for diffusion. AbhinavPJ's quantum simulation was a topic reference; no source code, notebook, figure, or dataset was copied. See [related work](../docs/RELATED_WORK.md) and the [method report](../docs/METHOD.md).
'''
    (directory/'METHOD_COMPARISON.md').write_text(report)
    print(json.dumps({'cases':len(rows),'best_max_error':min(row[4] for row in rows)},indent=2))


if __name__ == '__main__':
    main()
